name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile the project
        run: mvn test-compile -pl retrofit -am
  
      - name: Run tests
        run: mvn -pl retrofit test -Dtest=retrofit2.CompletableFutureAndroidTest#completableFutureApi24
  
      - name: Run NonDex to check for flaky tests
        run: mvn -pl retrofit edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=retrofit2.CompletableFutureAndroidTest#completableFutureApi24 -DnondexRuns=10
